const Boards = {
  COORDENACAO_GERAL: 0,
  TECNOLOGIA_DA_INFORMACAO: 1,
  DESIGN_E_MARKETING: 2,
  CONTEUDO: 3,
  PATROCINIO: 4,
  JURIDICO_FINANCEIRO: 5,
  SOCIO_CULTURAL: 6,
};

export default Boards;
